### ISSUE TITLE
Functionality and use of external services are unclear

### ISSUE THREAD

**Issue by bencomp** [europeana/REPOX#15]
As a user of REPOX, it is completely unclear what I can use external services for and how I should configure them. The [manual for version 2.0.16](http://repox.sysresearch.org/doc/REPOX_Light_User%20Manual-V2.0.16.pdf) provides incomplete documentation of what each field in the configuration screen of an external service means and that is all I could find.

Can the wiki and readme be expanded with use cases and examples of external services that can be used with REPOX?

**Comment by stzanakis** [comment]
This functionality is basically to call rest api methods before or after the ingestion of a dataset.
So once you add the external service information you have to add it to the specific dataset you want it be called.
These information cannot go in the README, maybe we will incorporate it in the wiki pages or make another User Documentation in a future release. I will open a ticket for it.

**Comment by bencomp** [comment]
Thanks for the info. The README is probably not the best choice for this information, I agree. 

So it cannot be used to fix up individual records before ingest? And it cannot be used to start workflows after an export, because calls are linked to ingest actions?

What kind of calls are made? POST or GET? How does REPOX use the given status URI? How does it use the external results URI?

What is the semantics for each particular option for the `Semantics` choice?

**Comment by stzanakis** [comment]
Sorry for the late reply, didn't have time to look into it until now. 
This is something that is actually outdated.
I had to dig in the code to find some more info.

So here are some of the answers:
External services are related to only ingesting tasks. PRE/POST.
They are simple GET methods since the new URL(String) and Document read is used.
The status URI basically polls the result until the function that the GET method triggered is finished. So you need another Status service that will keep the status. No monitor means you trigger the GET method and you just get the response and finish.
And the external results URI looks like it's not being used.

So conclusion, the code on that part is old and outdated(I think it was developed for a specific case in the past so it's not really generic) and we are not going to update it anytime soon.

**Comment by bencomp** [comment]
Thanks for the reply. There might be a good use for this feature, so please don't remove it without further discussion.

**Comment by stzanakis** [comment]
The functionality of the external services won't change, unless otherwise decided
