### ISSUE TITLE
Problems applying a stylesheet to a dataset

### ISSUE THREAD

**Issue by CanOfBees** [europeana/REPOX#4]
Hi again. 

I'm having some difficulty applying a stylesheet to a dataset. I've uploaded several test stylesheets, including samples from a [REPOX friendly repo](https://github.com/ncdhc/dpla-sample-repox-xslt). 

After adding the stylesheets via the MDR, I select a dataset > right-click > Edit Data Set > OAI-PMH tab > Under Output, Add a stylesheet > and Save. After adding the stylesheet, I've tried Ingest Now and  Export Now, in addition to trying things like Empty Data Set > Ingest Now.

Selecting either of the 'oai_dc' links in the following screenshot yield non-transformed records.
![data-set](https://cloud.githubusercontent.com/assets/2052902/5764807/dddea5c6-9cc2-11e4-9713-405e9e737f29.png)

I'm sure I'm missing something obvious, but I'm not sure what. Are the steps above the correct way to apply a stylesheet? Thanks again for your help.

**Comment by stzanakis** [comment]
Hello,

Ingesting will always give you the data in the format you ingest them.
To transform your data you need to use the export option.

**Comment by CanOfBees** [comment]
Okay - that answers another question we had. :) Unfortunately, in both 2.3.7 and 2.6.0, when I do either of the following: 

1. select a data set > right-click > 
2. Export Now > 
3. select number of records per file, Full Path to the export directory, and Export Format (there are two oai_dc options here; both yield the same result) > click Export

or
1. select a data set > right-click >
2. Schedule Export > 
3. select the appropriate options (and there is only one Export Format option here) > click Schedule > wait...

4. review the files in $full_path/to/export_directory and the exported files are unchanged.

I'm beginning to suspect my stylesheet is the problem. It works in a debugger (e.g. oXygen's XSLT debugger) and it works with saxon9he.jar on the command line, although I do get a warning in oXygen regarding namespaces. I have one of the stylesheets [in a repository](https://github.com/CanOfBees/repox-xsl-tests) -- could the issue be here?

**Comment by stzanakis** [comment]
Your xslt looks fine and I even tested it and is working correctly so I think you are missing some steps.

**Adding a Transformation**
1. MDR Tab
2. New Transformation
3. Complete the form(e.g. Source Format=oai_dc, Destination Format=Since you don't aim on a destination format, choose whatever, etc) and save

**Apply a Transformation to a dataset**
1. Home Tab
2. Right click dataset -> edit dataset
3. Transformation Box -> Add -> Choose the one you just added -> Add selected
4. Save Dataset

**Exporting**
1. Right Click on dataset
2. Export Now
3. Choose the transformation(based on the Destination Format you chose before)
4. Export

Now you should have the transformed ones.

**Comment by CanOfBees** [comment]
stzanakis -- thank you! That seems to have solved this problem.
