### ISSUE TITLE
repox-commons not accessible from artifactory.eanadev.org?

### ISSUE THREAD

**Issue by fruviad** [europeana/REPOX#45]
mvn dependency:tree results in:

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.776 s
[INFO] Finished at: 2021-12-19T03:32:17Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project repox-manager: Could not resolve dependencies for project repox:repox-manager:jar:3.2.1-SNAPSHOT: Could not transfer artifact repox:repox-commons:jar:3.2.1-SNAPSHOT from/to artifactory.eanadev.org (http://artifactory.eanadev.org/artifactory/ext-release-local): Transfer failed for http://artifactory.eanadev.org/artifactory/ext-release-local/repox/repox-commons/3.2.1-SNAPSHOT/repox-commons-3.2.1-SNAPSHOT.jar 409 Conflict -> [Help 1]

Hitting https://artifactory.eanadev.org/artifactory/ext-release-local/repox/ with a browser shows only a "repox-gui" subdirectory.

Are these files available any longer?

**Comment by stzanakis** [comment]
Hi fruviad,

We don't support REPOX anymore.
I don't know why it tried to get the snapshot from the release repository, that's why it fails. It should get it from the equivalent snapshot repository. Nonetheless that version might not even be in the snapshot.
You could perhaps build the root project locally though which will result in creating the snapshot on your local repo.
Hope that helps!
