### ISSUE TITLE
mysql db setup

### ISSUE THREAD

**Issue by neshelman** [europeana/REPOX#9]
Hi SImon, I see in
./WEB-INF/classes/configuration.properties
where you define the dbname, user and password. What else needs to be done to connect repox to a mysql db? What does the schema look like? What is the db used for? Thanks --Nicholas

**Comment by stzanakis** [comment]
Hello Nicholas,

The database is used for storing your records and incremental information.
In the file `configuration.properties` are the settings for your database. This file is located in the resource module and if you want different values you can modify the file on the resources module and rebuild repox. 
Another thing you can do is add a separate configuration file independent of the build, by declaring a JVM system variable of the directory where the required configuration.properties file is located, like so `repox.data.dir=/path/to/configuration/dir` . This means that repox will be using your independent configuration instead of the one that in `./WEB-INF/classes/configuration.properties` . Though I recommend using the default method.

Obviously for the database you need to create a simple schema and a user that can access it.
